/** Chrome strings for the Cloudflare Pages vetrina. Listing body stays in playstore/copy.mjs. */

export const HOSTING_ORIGIN = "https://mobilespinroulette.pages.dev";
export const ITCH_URL = "https://bitcroupier.itch.io/mobile-roulette";
export const GITHUB_URL = "https://github.com/orfeomorello/OpenSource-Mobile-Spin-Roulette";

export const hostingChrome = {
  en: {
    play: "Play online",
    playHint: "Free in the browser on itch.io",
    github: "Source on GitHub",
    privacy: "Privacy",
    languages: "Language",
    gallery: "The table",
    shotHome: "Home",
    shotTable: "Phone · portrait",
    shotLandscape: "Phone · landscape",
    shotTablet: "Tablet",
    licenseShort: "Software GPL-3.0-or-later. Music and Inter keep their original licenses.",
    footer: "Open source · Virtual points only · Not a casino",
    skip: "Skip to content",
    chooseLang: "Choose language",
  },
  it: {
    play: "Gioca online",
    playHint: "Gratis nel browser su itch.io",
    github: "Codice su GitHub",
    privacy: "Privacy",
    languages: "Lingua",
    gallery: "Il tavolo",
    shotHome: "Home",
    shotTable: "Telefono · verticale",
    shotLandscape: "Telefono · orizzontale",
    shotTablet: "Tablet",
    licenseShort: "Software GPL-3.0-or-later. Musica e Inter restano sulle licenze originali.",
    footer: "Open source · Solo punti virtuali · Non è un casinò",
    skip: "Vai al contenuto",
    chooseLang: "Scegli la lingua",
  },
  es: {
    play: "Jugar en línea",
    playHint: "Gratis en el navegador en itch.io",
    github: "Código en GitHub",
    privacy: "Privacidad",
    languages: "Idioma",
    gallery: "La mesa",
    shotHome: "Inicio",
    shotTable: "Teléfono · vertical",
    shotLandscape: "Teléfono · horizontal",
    shotTablet: "Tableta",
    licenseShort: "Software GPL-3.0-or-later. La música e Inter conservan sus licencias originales.",
    footer: "Código abierto · Solo puntos virtuales · No es un casino",
    skip: "Saltar al contenido",
    chooseLang: "Elegir idioma",
  },
  "pt-BR": {
    play: "Jogar online",
    playHint: "Grátis no navegador no itch.io",
    github: "Código no GitHub",
    privacy: "Privacidade",
    languages: "Idioma",
    gallery: "A mesa",
    shotHome: "Início",
    shotTable: "Celular · retrato",
    shotLandscape: "Celular · paisagem",
    shotTablet: "Tablet",
    licenseShort: "Software GPL-3.0-or-later. A música e a Inter mantêm as licenças originais.",
    footer: "Código aberto · Só pontos virtuais · Isto não é um cassino",
    skip: "Ir ao conteúdo",
    chooseLang: "Escolher idioma",
  },
  fr: {
    play: "Jouer en ligne",
    playHint: "Gratuit dans le navigateur sur itch.io",
    github: "Code sur GitHub",
    privacy: "Confidentialité",
    languages: "Langue",
    gallery: "La table",
    shotHome: "Accueil",
    shotTable: "Téléphone · portrait",
    shotLandscape: "Téléphone · paysage",
    shotTablet: "Tablette",
    licenseShort: "Logiciel GPL-3.0-or-later. La musique et Inter gardent leurs licences d’origine.",
    footer: "Open source · Points virtuels uniquement · Ce n’est pas un casino",
    skip: "Aller au contenu",
    chooseLang: "Choisir la langue",
  },
  de: {
    play: "Online spielen",
    playHint: "Kostenlos im Browser auf itch.io",
    github: "Quelltext auf GitHub",
    privacy: "Datenschutz",
    languages: "Sprache",
    gallery: "Der Tisch",
    shotHome: "Start",
    shotTable: "Handy · Hochformat",
    shotLandscape: "Handy · Querformat",
    shotTablet: "Tablet",
    licenseShort: "Software GPL-3.0-or-later. Musik und Inter behalten ihre ursprünglichen Lizenzen.",
    footer: "Open Source · Nur virtuelle Punkte · Das ist kein Casino",
    skip: "Zum Inhalt",
    chooseLang: "Sprache wählen",
  },
  ko: {
    play: "온라인으로 플레이",
    playHint: "브라우저에서 무료 · itch.io",
    github: "GitHub 소스",
    privacy: "개인정보",
    languages: "언어",
    gallery: "테이블",
    shotHome: "홈",
    shotTable: "휴대폰 세로",
    shotLandscape: "휴대폰 가로",
    shotTablet: "태블릿",
    licenseShort: "소프트웨어는 GPL-3.0-or-later. 음악과 Inter는 원래 라이선스를 유지합니다.",
    footer: "오픈 소스 · 가상 점수만 · 카지노가 아닙니다",
    skip: "본문으로",
    chooseLang: "언어 선택",
  },
  ja: {
    play: "オンラインで遊ぶ",
    playHint: "ブラウザ無料 · itch.io",
    github: "GitHub のソース",
    privacy: "プライバシー",
    languages: "言語",
    gallery: "テーブル",
    shotHome: "ホーム",
    shotTable: "スマホ縦",
    shotLandscape: "スマホ横",
    shotTablet: "タブレット",
    licenseShort: "ソフトウェアは GPL-3.0-or-later。音楽と Inter は元のライセンスのままです。",
    footer: "オープンソース · 仮想ポイントのみ · カジノではありません",
    skip: "本文へ",
    chooseLang: "言語を選択",
  },
  zh: {
    play: "在线游玩",
    playHint: "浏览器免费 · itch.io",
    github: "GitHub 源码",
    privacy: "隐私",
    languages: "语言",
    gallery: "牌桌",
    shotHome: "主页",
    shotTable: "手机竖屏",
    shotLandscape: "手机横屏",
    shotTablet: "平板",
    licenseShort: "软件采用 GPL-3.0-or-later。音乐和 Inter 保留原许可。",
    footer: "开源 · 仅虚拟积分 · 不是赌场",
    skip: "跳到正文",
    chooseLang: "选择语言",
  },
};
